from church_encodings.pair import p_pair, p_first, p_second
from church_encodings.bool import b_false, b_true

l_nil = ...
l_cons = ...

l_append = ...
l_is_nil = ...
l_is_non_empty = ...
l_head = ...
l_tail = ...

l_filter = ...
l_map = ...
l_flat_map = ...

l_at = ...
